### PR TITLE
Fix for #127

### PR DESCRIPTION
**Pull request by brachna**
Bandcamp scraper was sanitizing artist for path with -f, but not without. Now it does.

### CODE REVIEW

**Comment by brachna** [comment]
Damn, I didn't want two different commits in one pull...

**Comment by brachna** [comment]
Referencing issue #129

**Comment by Miserlou** [comment]
Thanks. I've been getting really sloppy with merging PR's on the project lately..

**Comment by brachna** [comment]
np, real life comes first

**Pull request merged**
