### PR TITLE
fix for #112

### PR DESCRIPTION
**Pull request by brachna**
Done by wrapping puts() calls into puts_safe(). Non-printable characters are replaced with '?'
2 calls that use plain english are left as puts().

I'm on Windows and can say that now it doesn't crash on https://archivesdubmusic.bandcamp.com/album/debut

### CODE REVIEW

**Comment by brachna** [comment]
hmm, travis check fails

**Comment by Miserlou** [comment]
Hm, I don't think this will work judging by those errors.

Might be worth taking a look at how the 'click' package handles this..

**Comment by brachna** [comment]
Does current master pass travis? Strange that it fails, it should affect only console print text.

**Comment by Miserlou** [comment]
Current master passes, yes. These errors are specific to the new change. =/

**Comment by brachna** [comment]
Ok, I'm discarding this pull then. Strange that it fails.

**Comment by Miserlou** [comment]
Well, I think it can be salved, just need to figure what's going on and fix the error! :D

**Comment by brachna** [comment]
Hurray? Apparently Linux didn't like that line.

**Comment by Miserlou** [comment]
Good enough for me

**Comment by Miserlou** [comment]
Thanks for your contribution!

**Pull request merged**
